database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable" # или "require", в зависимости от требований

storage:
  isInMemoryStorage: false