database:
  driver: "postgres"
  host: "postgres"
#  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "calendar_db"
  sslmode: "disable" # или "require", в зависимости от требований
  isInMemoryStorage: false
  migrationPath: "etc/migrations"
#  migrationPath: "migrations"

server:
  host: "calendar-app"
#  host: "localhost"
  port: 8081

logger:
  enabled: true
  level: "info"

grpc:
  host: "calendar-app"
#  host: "localhost"
  port: "50051"