database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "calendar_db"
  sslmode: "disable" # или "require", в зависимости от требований
  isInMemoryStorage: false
  migrationPath: "migrations"

server:
  host: "localhost"
  port: 8081

logger:
  enabled: true
  level: "info"

rmq:
  uri: "amqp://test:test@localhost:5672/"
  reConnect:
    maxElapsedTime: "1m"
    initialInterval: "1s"
    multiplier: 2
    maxInterval: "15s"

binding:
  exchangeName: ""
  exchangeType: "fanout"
  queueName: "notifications"
  bindingKey: ""

kafka:
  broker: "localhost:9092" # Адрес брокера Kafka
  consumer:
    groupID: "calendar_notifications_group" # ID группы для потребителей
    topic: "notifications" # Топик, на который подписывается потребитель
    autoOffsetReset: "earliest" # Параметр для управления смещением
    maxPollRecords: 10 # Максимальное количество записей для выборки за один раз
    threads: 4 # Количество потоков для обработки сообщений
  producer:
    topic: "notifications" # Топик, в который будет отправляться сообщение